name: OTS Action

on:
    workflow_dispatch:
        inputs:
            server_url:
                description: 'Server URL'
                required: true
            offline_token:
                description: 'Offline Token'
                required: true
            team_space:
                description: 'Team Space'
                required: true
            project:
                description: 'Project'
                required: true
            branch:
                description: 'Branch'
                required: true
            repository:
                description: 'Repository'
                required: true
            file_path:
                description: 'File Path'
                required: true
            environment:
                description: 'Environment'
                required: true

jobs:

    OTS-Action:
        runs-on: ubuntu-latest
        name: Execute OTS Test
        steps:
         - name: _prop_action_server_name_ Action
           uses: SonaHJ/OTSAction@ReleaseOTS
           with:
            serverUrl: '${{ github.event.inputs.server_url }}'
            offlineToken: '${{ github.event.inputs.offline_token }}'
            teamspace: '${{ github.event.inputs.team_space }}'
            project: '${{ github.event.inputs.project }}'
            branch: '${{ github.event.inputs.branch }}'
            repository: '${{ github.event.inputs.repository }}'
            filepath: '${{ github.event.inputs.file_path }}'
            environment: '${{ github.event.inputs.environment }}'
    Test-Action:
        runs-on: ubuntu-latest
        name: OTS Test
        steps:
         - name: Execute Test2
           uses: SonaHJ/OTSAction@main
           with:
            serverUrl: '${{ github.event.inputs.server_url }}'
