name: PR metadata annotation

on: 
  workflow_dispatch:

jobs:

  annotate-pr:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: _prop_action_server_name_ Action
        uses: SonaHJ/OTSAction@ReleaseOTS
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
